name: Example Workflow

on: [push]  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Test
        run: ls ; pwd ; ls -ltra ; hostname
